version: '3.3'

services:
  server:
    ports:
    - 443:443
    - 4443:4443
    build:
      context: .
    volumes:
      - "${KEYS_PATH?err}:/keys" # fullchain.pem privkey.pem
    # disable insecure http
    entrypoint: /go/bin/ngrokd -domain ${DOMAIN?err} -httpAddr="" -tlsCrt="/keys/fullchain.pem" -tlsKey="/keys/privkey.pem"